input_path: data/processed/train.txt
eval_path: data/processed/test.txt
model_dir: models/
vocab_sizes:
  - 8000
  - 16000
model_type: unigram
character_coverage: 0.9995
pad_id: 0
unk_id: 1
bos_id: 2
eos_id: 3
user_defined_symbols:
  - "[MASK]"
  - "[PAD]"
byte_fallback: true
split_by_whitespace: true
